language: c++

os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake . ; fi
  - cmake -Dtest=on .
  - make -j2
  - make test
  - ls
  - cmake -Dmode=static .
  - make -j2
  - ls

deploy:
  - provider: releases
    api_key: "${token}"
    file:
      - "libmodio.so"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME != "osx"
  - provider: releases
    api_key: "${token}"
    file:
      - "libmodio.dylib"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME == "osx"