image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    .\appveyor_build_config.bat

after_build:
  - 7z a Windows.zip dynamic_build\Release\* static_build\Release\* dynamic_build_64bits\Release\* static_build_64bits\Release\* 

test_script:
- cmd: ctest -C Release

artifacts:
  - path: Windows.zip
    name: Windows

deploy:
  provider: GitHub
  auth_token:
    secure: "mPa2q6gkctTgPbec+bAGiPew2J7ehiDHalv4DW9H+RzIxgKZGr/ELPc9sLTVGlIB"
  artifact: Windows
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true