image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir dynamic_build

    cd dynamic_build

    cmake -G "Visual Studio 15" c:\projects\source

    cmake --build . --config "Release"

    mkdir ../static_build

    cd ../static_build

    cmake -D mode=static -G "Visual Studio 15" c:\projects\source

    cmake --build . --config "Release"

    mkdir ../dynamic_build_64bits

    cd ../dynamic_build_64bits

    cmake -G "Visual Studio 15 Win64" c:\projects\source

    cmake --build . --config "Release"

    mkdir ../static_build_64bits

    cd ../static_build_64bits

    cmake -D mode=static -G "Visual Studio 15 Win64" c:\projects\source

    cmake --build . --config "Release"

    cd ..

after_build:
  - dir
  - 7z a Windows.zip dynamic_build\Release\* static_build\Release\* dynamic_build_64bits\Release\* static_build_64bits\Release\* 

test_script:
- cmd: ctest -C Release

artifacts:
  - path: dynamic_build\Release\
    name: WindowsDynamic
  - path: static_build\Release\
    name: WindowsStatic
  - path: dynamic_build_64bits\Release\
    name: WindowsDynamic64bits
  - path: static_build_64bits\Release\
    name: WindowsStatic64bits
  - path: Windows.zip
    name: Windowss

deploy:
  provider: GitHub
  auth_token:
    secure: "mPa2q6gkctTgPbec+bAGiPew2J7ehiDHalv4DW9H+RzIxgKZGr/ELPc9sLTVGlIB"
  artifact: WindowsDynamic, WindowsStatic, WindowsDynamic64bits, WindowsStatic64bits, Windowss
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true