image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir dynamic_build

    cd dynamic_build

    cmake c:\projects\source -G "Visual Studio 15"

    cmake --build . --config "Release"

    cd ..

    mkdir static_build

    cd static_build

    cmake -Dmode=static -G "Visual Studio 15" c:\projects\source

    cmake --build . --config "Release"

    cd ..

    mkdir dynamic_build_64bits

    cd dynamic_build_64bits

    cmake c:\projects\source -G "Visual Studio 15 Win64"

    cmake --build . --config "Release"

    mkdir static_build_64bits

    cd static_build_64bits

    cmake -Dmode=static -G "Visual Studio 15 Win64" c:\projects\source

    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Release

artifacts:
  - path: dynamic_build\Release\
    name: WindowsDynamic
  - path: static_build\Release\
    name: WindowsStatic
  - path: dynamic_build_64bits\Release\
    name: WindowsDynamic64bits
  - path: static_build_64bits\Release\
    name: WindowsStatic64bits

deploy:
  provider: GitHub
  auth_token:
    secure: "mPa2q6gkctTgPbec+bAGiPew2J7ehiDHalv4DW9H+RzIxgKZGr/ELPc9sLTVGlIB"
  artifact: WindowsDynamic, WindowsStatic, WindowsDynamic64bits, WindowsStatic64bits
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true