image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    .\appveyor_build_config.bat
test_script:
- cmd: >-
    test_build\Debug\runUnitTests.exe
artifacts:
  - path: Windows.zip
    name: Windows

deploy:
  provider: GitHub
  auth_token:
    secure: "mPa2q6gkctTgPbec+bAGiPew2J7ehiDHalv4DW9H+RzIxgKZGr/ELPc9sLTVGlIB"
  artifact: Windows
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true