image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build
    
    cmake c:\projects\source -G "Visual Studio 15"
    
    cmake --build . --config "Release"

    dir

    dir Release

    cd ..

    mkdir buildStatic

    cd buildStatic

    cmake -Dmode=static -G "Visual Studio 15" c:\projects\source

    cmake --build . --config "Release"

    dir

    dir Release

test_script:
- cmd: ctest -C Release

artifacts:
  - path: build\Release\
    name: DynamicRelease
  - path: buildStatic\Release\
    name: StaticRelease

deploy:
  description: 'Release description huh'
  provider: GitHub
  auth_token:
    secure: "mPa2q6gkctTgPbec+bAGiPew2J7ehiDHalv4DW9H+RzIxgKZGr/ELPc9sLTVGlIB"
  artifact: DynamicRelease, StaticRelease
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true